name: Java CI + Agentic DevOps

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ---------------- Base Setup ----------------
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # ---------------- Agentic Pre-Steps ----------------
      - name: Install Python deps for Agents
        run: |
          python -m pip install --upgrade pip
          pip install openai dspy requests pyyaml

      - name: Run Pre-Config & PR Reviewer Agents
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🔍 Running Pre-Config & PR Reviewer Agents"
          python agents/preconfig_gate.py
          python agents/pr_reviewer.py

      # ---------------- Build/Test Stage ----------------
      - name: Build & Test with Gradle
        id: gradle
        run: ./gradlew clean test | tee build.log

      # ---------------- Pipeline RCA on Failure ----------------
      - name: Run Pipeline RCA Agent
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🚨 Running Pipeline RCA Agent"
          python agents/pipeline_rca.py

      # ---------------- Security Watcher on Success ----------------
      - name: Build Docker Image
        if: success()
        run: docker build -t springboot-agentic:latest .

      - name: Run Trivy Scan
        if: success()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: springboot-agentic:latest
          format: json
          output: trivy-report.json

      - name: Run Security Watcher Agent
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🛡️ Running Security Watcher Agent"
          python agents/security_watcher.py

      # ---------------- Summary ----------------
      - name: Workflow Summary
        if: always()
        run: |
          echo "✅ Agentic DevOps pipeline finished."
