name: Java CI

on:
  pull_request:
    branches: ['**']

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Test with Gradle
        id: gradle
        run: ./gradlew clean test | tee build.log

      # 🔥 Only runs when build/test fails
      - name: Run Pipeline RCA Agent
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python agents/pipeline_rca.py

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log

      - name: Summary
        if: always()
        run: echo "✅ Java CI complete."
